# Generated by Django 5.1.6 on 2025-02-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CP', 'Congé payé'), ('RTT', 'RTT'), ('CM', 'Congé maladie'), ('SansSolde', 'Congé sans solde')], default='CP', max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
