# Generated by Django 5.1.6 on 2025-05-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0002_update_fiscal_power'),
        ('rh_management', 'update_fiscal_power'),
    ]

    operations = [
    ]
