# Generated by Django 5.1.6 on 2025-02-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0002_leaverequest_leave_type_alter_leaverequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensereport',
            name='created_at',
        ),
        migrations.AddField(
            model_name='expensereport',
            name='currency',
            field=models.CharField(default='€', max_length=10),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='refacturable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10),
        ),
    ]
