# Generated by Django 5.1.6 on 2025-02-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0004_kilometricexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilometricexpense',
            name='location',
        ),
        migrations.RemoveField(
            model_name='kilometricexpense',
            name='project',
        ),
        migrations.RemoveField(
            model_name='kilometricexpense',
            name='refacturable',
        ),
        migrations.AddField(
            model_name='kilometricexpense',
            name='arrival_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kilometricexpense',
            name='arrival_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kilometricexpense',
            name='departure_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kilometricexpense',
            name='departure_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kilometricexpense',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
