# Generated by Django 5.1.6 on 2025-02-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0006_kilometricexpense_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='kilometricexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
