# Generated by Django 5.1.6 on 2025-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0007_alter_expensereport_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
