# Generated by Django 5.1.6 on 2025-03-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0009_kilometricexpense_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='media/receipts/'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='media/receipts/'),
        ),
    ]
