# Generated by Django 5.1.6 on 2025-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0010_leaverequest_attachment_alter_expensereport_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='notification_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
