# Generated by Django 5.1.6 on 2025-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0011_expensereport_notification_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
