# Generated by Django 5.1.6 on 2025-03-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0014_kilometricexpense_notification_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensereport',
            name='notification_emails',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='notification_emails',
        ),
    ]
