# Generated by Django 5.1.6 on 2025-03-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0015_remove_expensereport_notification_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='notification_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='notification_emails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
