# Generated by Django 5.1.6 on 2025-03-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0017_alter_expensereport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensereport',
            name='currency',
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10),
        ),
    ]
