# Generated by Django 5.1.6 on 2025-03-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0018_remove_expensereport_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kilometricexpense',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Voiture'), ('electric_car', 'Voiture électrique'), ('motorbike', 'Moto'), ('bike', 'Vélo')], max_length=20),
        ),
    ]
