# Generated by Django 5.1.6 on 2025-03-20 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0021_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.FloatField(default=0.0, help_text='Total des jours de congés acquis')),
                ('taken', models.FloatField(default=0.0, help_text='Total des jours de congés pris')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
