# Generated by Django 5.1.6 on 2025-03-20 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0022_leavebalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilometricexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
