# Generated by Django 5.1.6 on 2025-03-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0026_alter_expensereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='expense_type',
            field=models.CharField(choices=[('transport', 'Transport'), ('meal', 'Repas'), ('accommodation', 'Hébergement'), ('supplies', 'Fournitures'), ('communication', 'Communication'), ('representation', 'Frais de représentation'), ('other', 'Autre')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='expense_attachments/'),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='project',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
