# Generated by Django 5.1.6 on 2025-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0028_remove_userprofile_is_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='days_requested',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
