# Generated by Django 5.1.6 on 2025-03-27 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh_management', '0029_leaverequest_days_requested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Permission personnalisée',
                'verbose_name_plural': 'Permissions personnalisées',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.ManyToManyField(to='rh_management.custompermission')),
                ('users', models.ManyToManyField(related_name='custom_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Groupe de permissions',
                'verbose_name_plural': 'Groupes de permissions',
                'ordering': ['name'],
            },
        ),
    ]
